### ISSUE TITLE
Ftp backups - purge

### ISSUE THREAD

**Issue by MrSiO** [leinich/hassio-addons#10]
Hi sir.

Is there a way to configure a purge for backups older then X days?

Found out my disk was full due to all the old backups stored in /use/share/hassio/backup...

Such feature would prevent this...

Thx.

**Comment by leinich** [comment]
@MrSiO 
sure that would be possible.
Deleting files in the backup folder older than x days would delete any file matched this criteria in the backup folder.
Should we check for any naming convention here?
I'm not sure if the folder ist used by any other plugin/integration/addon

**Comment by europer** [comment]
Hi, did edit my text, did your url to work again.
Question, like the simple easy way of the backup, what would be "nice to have" is say the days&time to make the backup, it there a way to do this?
thanks
Per

**Comment by leinich** [comment]
> Hi, did edit my text, did your url to work again.
> Question, like the simple easy way of the backup, what would be "nice to have" is say the days&time to make the backup, it there a way to do this?
> thanks
> Per

You can use the automation feature in ha to specify the date & time.
Like here: https://github.com/leinich/hassio-addons/issues/5
