### ISSUE TITLE
ftp backup randomly stops

### ISSUE THREAD

**Issue by TerrorSource** [leinich/hassio-addons#7]
Hi,

Using FTP Backup with latest HA installed on a Pi.
It randomly stops.

It can be reproduced by installing FTP Backup from the repo, set it up, start it
Then launch it via an Automation. FTP Backup stops after a few seconds.

Also, why doesnt FTP backup remove the files in /backup/ dir when uploaded?

```
[Info] Finished archiving configuration
[Info] trying to upload /backup/homeassistant_backup_20200623113649.zip to ftp://192.168.x.x:21/backup/homeassistant_2/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3  108M    0     0    3 4352k      0  10.9M  0:00:09 --:--:--  0:00:09 10.9M
100  108M    0     0  100  108M      0  81.5M  0:00:01  0:00:01 --:--:-- 81.5M
[Info] Finished ftp backup
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by leinich** [comment]
Dear @TerrorSource 
> FTP Backup stops after a few seconds.
This addon is desiged in such way:
1. ZIP Archive creation 
2. Upload 
3. Stop
Once it is finished the addon will always stop. So this is an intended behaviour.
There is no need to keep the addon running and using any ressource.

> Also, why doesnt FTP backup remove the files in /backup/ dir when uploaded?
I keep my backups on the SD Card of my Raspberry Pi and on the target FTP Server.
If I need space on the Raspberry Pi i delete the not needed backups.

Please feel free to add an option to delete the backup. PR are welcome.
